name: Security Checks

on: pull_request

permissions:
  contents: read

jobs:
  security:
    name: Security Checks
    runs-on: ubuntu-20.04
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        continue-on-error: true
        with:
          output_format: cli,sarif
          output_file_path: console
          quiet: true
