name: Lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  actionlint:
    name: GitHub Actions
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Lint GitHub Actions Workflow Files
        uses: docker://rhysd/actionlint@sha256:daa1edae4a6366f320b68abb60b74fb59a458c17b61938d3c62709d92b231558 # v1.6.27
        with:
          args: -color
  yamllint:
    name: YAML
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Setup Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: 3.12
      - name: Install yamllint
        run: |
          pip install --upgrade pip
          pip install yamllint
      - name: Lint YAML Files
        run: |
          yamllint .
  terraform-fmt:
    name: Terraform
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.8.0
      - name: Lint Terraform Files
        run: |
          terraform fmt -recursive -check
  tflint:
    name: TFLint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.9.0
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.53.0
      - name: TFLint
        run: |
          tflint --init
          tflint --recursive --format=compact
  terraform-docs:
    name: Terraform Docs
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request' && contains(github.repository, 'template') == false
    ## Allow updating of PR branch TF Docs
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Generate Docs
        uses: terraform-docs/gh-actions@e47bfa196e79fa50987ef391be236d9d97b0c786 # v1.2.0
        with:
          fail-on-diff: true
          git-push: "true"
