name: Pre-release

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read
  contents: read

jobs:
  title:
    name: Semantic Title
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # 5.5.3
        with:
          types: |
            docs
            ci
            fix
            feat
            major
          requireScope: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tftest:
    name: Terraform Test
    runs-on: ubuntu-22.04
    needs: title
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.9.0
      - name: Run Tests
        run: terraform test
  terraform-docs:
    name: Terraform Docs
    runs-on: ubuntu-22.04
    needs: tftest
    ## Allow updating of PR branch TF Docs
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Generate Docs
        uses: terraform-docs/gh-actions@e47bfa196e79fa50987ef391be236d9d97b0c786 # v1.2.0
        with:
          indention: 3
          fail-on-diff: true
          git-push: "true"
