name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  tftest:
    name: Terraform Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.9.0
      - name: Run Tests
        run: terraform test
  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: tftest
    # Skip running release workflow on template repo
    if: contains(github.repository, 'template') == false
    outputs:
      version_number: ${{ steps.release.outputs.new_version_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Release
        id: release
        uses: cycjimmy/semantic-release-action@cb425203a562475bca039ba4dbf90c7f9ac790f4 # v4.1.0
        with:
          semantic_version: 23.0.5
          extra_plugins: |
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  push-module:
    name: Push Terraform Module
    runs-on: ubuntu-22.04
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - id: terraform-push-module
        uses: bruceharrison1984/terraform-push-module@1.0.0 ## ensure using latest version
        with:
          serverUri: https://app.terraform.io ## can be replaced with TFE URL
          organizationName: my-hcp-org
          moduleName: my-module
          authToken: ${{ secrets.TFE_TOKEN }} ## token should be securely stored in GitHub Secrets
          providerName: aws
          versionString: ${{ needs.release.outputs.version_number }} ## source version from release plugin
          isNoCode: "false"
      ## optionally save the tarball to Github Artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.terraform-push-module.outputs.moduleName }}@${{ steps.terraform-push-module.outputs.moduleVersion }}
          path: ${{ steps.terraform-push-module.outputs.archiveFilepath }}
